ALTER TABLE "tournaments"
ADD COLUMN "format" TEXT NOT NULL DEFAULT 'LEAGUE',
ADD COLUMN "roundTrip" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "pointsWin" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN "pointsDraw" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "pointsLoss" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "tiebreakers" JSONB NOT NULL DEFAULT '["GOAL_DIFF","GOALS_FOR","HEAD_TO_HEAD"]';
